"""Reapply hand-patches to the generated Lunch Money API types.

`lunchmoney/lm_api_types_generated.py` is committed to git as a normal source file
and is NOT auto-generated by the build. It was produced once by
datamodel-code-generator (see the `types` Makefile rule in git history) and then
patched by this script. If you ever regenerate it from the OpenAPI spec, run:

    .venv/bin/python lunchmoney/patch_generated_types.py lunchmoney/lm_api_types_generated.py

This fixes three things the generator cannot express on its own:

1. Optional-but-non-nullable fields. The request schemas mark fields as
   not-required and `nullable: false` ("omit = leave unchanged; if present, must
   be non-null"). The generator encodes "omittable" as a `= None` default but,
   under --strict-nullable, keeps the type non-optional, producing the unsound
   `field: str = None`. We widen the type to `str | None` so the None default is
   sound; partial requests are sent with `model_dump(exclude_unset=True)`.

2. An enum member shadowing a str/StrEnum builtin (`split` shadows str.split):
   renamed to `split_`, value unchanged.

3. A bare string default on an enum-typed field (`status: Status = "active"`)
   rewritten to the enum member (`Status.active`).
"""

import ast
import re
import sys


def main(path: str) -> None:
    src = open(path).read()
    tree = ast.parse(src)

    starts = []
    pos = 0
    for line in src.splitlines(keepends=True):
        starts.append(pos)
        pos += len(line)

    def off(lineno: int, col: int) -> int:
        return starts[lineno - 1] + col

    # (start, end, replacement) — applied right-to-left so offsets stay valid.
    edits: list[tuple[int, int, str]] = []

    for node in ast.walk(tree):
        if not (
            isinstance(node, ast.AnnAssign)
            and isinstance(node.value, ast.Constant)
            and node.value.value is None
        ):
            continue
        ann = node.annotation
        if (
            isinstance(ann, ast.Subscript)
            and isinstance(ann.value, ast.Name)
            and ann.value.id == "Annotated"
        ):
            inner = ann.slice.elts[0] if isinstance(ann.slice, ast.Tuple) else ann.slice
        else:
            inner = ann
        seg = ast.get_source_segment(src, inner)
        if seg is None or "None" in seg:
            continue
        assert inner.end_lineno is not None and inner.end_col_offset is not None
        end = off(inner.end_lineno, inner.end_col_offset)
        edits.append((end, end, " | None"))

    for m in re.finditer(r'^    split(?= = "split")', src, re.MULTILINE):
        edits.append((m.start(), m.end(), "    split_"))

    for m in re.finditer(r'\] = "active"$', src, re.MULTILINE):
        edits.append((m.start(), m.end(), "] = Status.active"))

    for start, end, text in sorted(edits, key=lambda e: e[0], reverse=True):
        src = src[:start] + text + src[end:]

    open(path, "w").write(src)
    print(f"applied {len(edits)} patches to {path}")


if __name__ == "__main__":
    main(sys.argv[1])
